# Generated by Django 3.0.8 on 2020-12-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('purpose', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
